TwatMagBundle_homepage:
    pattern:  /
    defaults: { _controller: TwatMagBundle:Page:index }
    requirements:
        _method:  GET

TwatMagBundle_about:
    pattern:  /about
    defaults: { _controller: TwatMagBundle:Page:about }
    requirements:
        _method:  GET

TwatMagBundle_contact:
    pattern:  /contact
    defaults: { _controller: TwatMagBundle:Page:contact }
    requirements:
        _method:  GET|POST

TwatMagBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: TwatMagBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+        