parameters:
#    twat_mag.example.class: Twat\MagBundle\Example

services:
#    twat_mag.example:
#        class: %twat_mag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
