Twat\MagBundle\Entity\MyObject:
    type: entity
    table: objects
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value:
            type: string
            length: 200

