twat_mag_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TwatMagBundle:Default:index }

twat_mag_blog:
    pattern: /blog/{word}
    defaults: { _controller: TwatMagBundle:Blog:index }

twat_mag_add_numbers:
    pattern: /add/{numberOne}/{numberTwo}
    defaults: { _controller: TwatMagBundle:Blog:add }
    requirements:
        numberOne: \d+
        numberTwo: \d+
